//! Mirror test for `src/api/completions.rs`. Calls `api::completions::run`
//! directly — no data-dir, no DB — proving the generated script is
//! byte-identical to what `clap_complete::generate` writes straight to
//! stdout, and that an unsupported shell name is a `BadRequest`
//! (`cli::completions::run` writes the same bytes to stdout, exercised in
//! `tests/cli_completions.rs`; the HTTP route lives in
//! `tests/serve__routes__meta.rs`).

use std::io::Write as _;

use clap::CommandFactory;
use comemory::api::{self, Ctx};
use comemory::cli::Cli;
use comemory::config::{Config, Paths};

fn request(shell: &str) -> api::completions::Request {
    api::completions::Request {
        shell: shell.to_string(),
    }
}

#[test]
fn run_bash_matches_generate_byte_for_byte() {
    let paths = Paths::new("/nonexistent-never-touched");
    let cfg = Config::defaults();
    let mut ctx = Ctx::lazy(&paths, &cfg);

    let script = api::completions::run(&mut ctx, request("bash")).expect("completions run");

    let mut cmd = Cli::command();
    let bin_name = cmd.get_name().to_string();
    let mut expected: Vec<u8> = Vec::new();
    clap_complete::generate(
        clap_complete::Shell::Bash,
        &mut cmd,
        bin_name,
        &mut expected,
    );
    assert_eq!(script.as_bytes(), expected.as_slice());
}

#[test]
fn run_accepts_every_documented_shell() {
    let paths = Paths::new("/nonexistent-never-touched");
    let cfg = Config::defaults();
    for shell in ["bash", "zsh", "fish", "powershell", "elvish"] {
        let mut ctx = Ctx::lazy(&paths, &cfg);
        let script = api::completions::run(&mut ctx, request(shell))
            .unwrap_or_else(|e| panic!("completions run for {shell}: {e}"));
        assert!(
            !script.trim().is_empty(),
            "{shell} completions must not be empty"
        );
        assert!(
            script.contains("comemory"),
            "{shell} completions must mention the binary name"
        );
    }
}

#[test]
fn run_rejects_an_unsupported_shell() {
    let paths = Paths::new("/nonexistent-never-touched");
    let cfg = Config::defaults();
    let mut ctx = Ctx::lazy(&paths, &cfg);

    let err = api::completions::run(&mut ctx, request("not-a-shell"))
        .expect_err("unsupported shell must be rejected");
    assert!(
        err.to_string().contains("invalid shell"),
        "unexpected error: {err}"
    );
}

#[test]
fn run_never_touches_the_data_dir() {
    // A path that does not exist and is never created: `run` must not stat,
    // create, or otherwise touch it — `comemory completions` has no DB.
    let paths = Paths::new("/nonexistent-never-touched");
    let cfg = Config::defaults();
    let mut ctx = Ctx::lazy(&paths, &cfg);
    api::completions::run(&mut ctx, request("fish")).expect("completions run");
    assert!(!paths.data_dir().exists());

    // Sanity-check the generated bytes are also writable to any sink
    // (mirrors the CLI's stdout write path).
    let mut ctx2 = Ctx::lazy(&paths, &cfg);
    let script = api::completions::run(&mut ctx2, request("fish")).expect("completions run");
    let mut buf: Vec<u8> = Vec::new();
    buf.write_all(script.as_bytes()).expect("write buf");
    assert_eq!(buf, script.into_bytes());
}
