//! `comemory completions <shell>` — emit a shell completion script on stdout.
//!
//! The script generation itself lives in `api::completions` (Binding Rule
//! 1); this CLI wrapper stays free of `Paths`/`Config` I/O — `completions`
//! has no DB and no config dependency, so it builds a throwaway `Ctx` and
//! writes the generated bytes to stdout unchanged. The `--json` and
//! `--data-dir` globals are accepted but ignored: this subcommand only
//! produces shell script text.

use std::io::Write as _;
use std::path::PathBuf;

use clap::Args as ClapArgs;
use clap_complete::Shell;

use crate::api::{self, Ctx};
use crate::config::paths::resolve_data_dir;
use crate::config::{Config, Paths};
use crate::prelude::*;

const EXAMPLES: &str = "\
Examples:
  # fish (autoloaded from this path)
  comemory completions fish > ~/.config/fish/completions/comemory.fish

  # zsh (homebrew site-functions path)
  comemory completions zsh > \"$(brew --prefix)/share/zsh/site-functions/_comemory\"

  # bash (homebrew bash-completion.d)
  comemory completions bash > \"$(brew --prefix)/etc/bash_completion.d/comemory\"

  # NOTE: scripts/dev-install.sh writes these automatically by default.";

/// Arguments for `comemory completions`.
#[derive(ClapArgs, Debug)]
#[command(after_help = EXAMPLES)]
pub struct Args {
    /// Shell to emit a completion script for.
    pub shell: Shell,
}

/// Emit the completion script for `a.shell` on stdout, via
/// `api::completions::run`. No data-dir I/O: `Paths`/`Config` are built but
/// never touched by the conn-free middle.
pub async fn run(a: Args, _json: bool, data_dir: Option<PathBuf>) -> Result<()> {
    let paths = Paths::new(resolve_data_dir(data_dir));
    let cfg = Config::defaults();
    let req = api::completions::Request {
        shell: a.shell.to_string(),
    };
    let mut ctx = Ctx::lazy(&paths, &cfg);
    let script = api::completions::run(&mut ctx, req)?;
    let mut out = std::io::stdout().lock();
    out.write_all(script.as_bytes())?;
    Ok(())
}
