#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
//! Test mirror for `src/domains/projects/slug.rs`: every vector the
//! platform's own `project-slug.ts` produced (fixture generated by bun from
//! comemory.io b86dec53, see `tests/fixtures/projects/platform_vectors.ts`).

use comemory::domains::projects::slug::{base_slug, disambiguate};
use serde_json::Value;

/// The committed platform vectors.
fn vectors() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/projects/platform_vectors.json"
    );
    serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap()
}

#[test]
fn base_slug_matches_every_platform_vector() {
    let vectors = vectors();
    let cases = vectors["baseSlug"].as_array().unwrap();
    assert!(cases.len() >= 12, "fixture lost its cases");
    for case in cases {
        let name = case["name"].as_str().unwrap();
        assert_eq!(base_slug(name), case["slug"].as_str().unwrap(), "{name:?}");
    }
}

#[test]
fn disambiguate_matches_every_platform_vector() {
    for case in vectors()["disambiguate"].as_array().unwrap() {
        let attempt = usize::try_from(case["attempt"].as_u64().unwrap()).unwrap();
        assert_eq!(
            disambiguate(case["base"].as_str().unwrap(), attempt),
            case["slug"].as_str().unwrap()
        );
    }
}
