//! The live-table allowlist pair behind [`super::run`]'s preservation copy,
//! plus the thin delegate that runs the allowlist sanity check before
//! handing off to [`crate::store::rebuild_copy`], which owns the actual
//! `ATTACH`/copy/`DETACH` lifecycle: everything a markdown replay cannot
//! reconstruct — the code index, the mined/earned code-graph edges plus
//! their per-repo cursors, the learning-loop counters, and the
//! document-domain tables.

use std::path::Path;

use crate::prelude::*;
use crate::store::Connection;

/// Every live table the preservation copy carries from the pre-rebuild
/// database. The single source both the copy passes (now in
/// `crate::store::rebuild_copy` and its siblings) and the `api::rebuild`
/// coverage integrity test read — never a regex over any copy module's SQL.
///
/// `edges` is here, not in [`RECONSTRUCTABLE_TABLES`], because the copy
/// narrows it to the three mined rel kinds (`co_changed`, `imports`,
/// `co_activated`); the memory-domain rels are replayed from markdown. That
/// partial copy is exactly why the live table must not be silently dropped
/// from either list.
pub(crate) const COPIED_TABLES: &[&str] = &[
    "code_symbols",
    "indexed_files",
    "code_fts",
    "code_vec",
    "edges",
    "repo_marker",
    "feedback",
    "code_feedback",
    "retrieval_log",
    "feedback_events",
    "query_expansions",
    "bandit_arms",
    "eval_runs",
    "gc_runs",
    "index_runs",
    "source_files",
    "documents",
    "document_chunks",
    "document_fts",
    "sync_log",
    "sync_state",
    "sync_binding",
];

/// Live tables a rebuild deliberately does not copy, each with its reason.
/// Every live table must appear in [`COPIED_TABLES`] or here — the
/// coverage test's other half.
pub(crate) const RECONSTRUCTABLE_TABLES: &[(&str, &str)] = &[
    ("memories", "replayed from memories/*.md"),
    ("memory_tags", "replayed from frontmatter"),
    ("memory_fts", "rebuilt by memory_row::insert"),
    ("memory_vec", "BYO-vector contract: caller re-embeds"),
    ("code_ref", "materialized from frontmatter references"),
    (
        "edge_fts",
        "regenerated by graph::derived::refresh_derived_best_effort",
    ),
    (
        "index_failures",
        "transient per-run index error log; not user data",
    ),
    (
        "source_roots",
        "reconciled from sources.toml by source::mirror",
    ),
    ("schema_meta", "owned by the migration runner"),
];

/// Run the allowlist sanity check, then attach `old_db` and copy every
/// preserved table into `conn` via [`crate::store::rebuild_copy`].
///
/// Caller must populate `main.source_roots` first
/// (`source::mirror::reconcile`, in [`super::build_new_db`]).
pub(crate) fn copy_preserved_tables_from_old(conn: &mut Connection, old_db: &Path) -> Result<()> {
    // Debug-only, and deliberately so: the authoritative check is
    // `migration_integrity_every_live_table_is_covered_exactly_once` in
    // `tests/coverage.rs`, which also proves the union covers the live set.
    // This assertion is not a runtime guard — it is what gives both consts a
    // real consumer in the non-test build, so neither can drift into
    // dead code while the coverage test still appears to pass.
    debug_assert!(
        COPIED_TABLES
            .iter()
            .all(|t| !RECONSTRUCTABLE_TABLES.iter().any(|(r, _)| r == t)),
        "a live table cannot appear in both COPIED_TABLES and RECONSTRUCTABLE_TABLES"
    );
    crate::store::rebuild_copy::copy_preserved_tables_from_old(conn, old_db)
}

#[cfg(test)]
#[path = "tests/coverage.rs"]
mod tests;
