//! The live-table allowlist pair behind [`super::run`]'s preservation copy,
//! plus the thin delegate that runs the allowlist sanity check before
//! handing off to [`crate::store::rebuild_copy`], which owns the actual
//! `ATTACH`/copy/`DETACH` lifecycle: everything a markdown replay cannot
//! reconstruct — the code index, the mined/earned code-graph edges plus
//! their per-repo cursors, the learning-loop counters, and the
//! document-domain tables.

use std::path::Path;

use crate::prelude::*;
use crate::store::Connection;

/// Every live table the preservation copy carries from the pre-rebuild
/// database. The single source both the copy passes (now in
/// `crate::store::rebuild_copy` and its siblings) and the `maintenance::rebuild`
/// coverage integrity test read — never a regex over any copy module's SQL.
///
/// `edges` is here, not in [`RECONSTRUCTABLE_TABLES`], because the copy
/// narrows it to the three mined rel kinds (`co_changed`, `imports`,
/// `co_activated`); the memory-domain rels are replayed from markdown. That
/// partial copy is exactly why the live table must not be silently dropped
/// from either list.
///
/// The `replica-v1` journal (#250) is copied for the same reason as the sync
/// tables, one step stronger: its sequences and receipts are the answers this
/// engine already gave peers. Re-deriving them from markdown would hand out
/// positions that were already issued and would turn every replayed operation
/// into a second effect. `replica_staged_part` is the exception — an upload
/// that never activated published nothing, so a peer re-stages it.
///
/// `memory_needs_embedding` (#251) is copied for the same reason: which
/// memories still owe a vector is a record of imports this engine refused,
/// and markdown carries no embedding at all, so a rebuild that dropped the
/// backlog would silently report a clean engine.
///
/// The #252 code generations are copied for the same reason as the replica
/// journal: a generation a peer accepted cannot be re-derived from a local
/// checkout, and dropping it would re-offer positions the peer already holds a
/// receipt for. The copy narrows to non-`staged` rows and carries the three
/// pulled-projection tables with the generations that survived, so a rebuild
/// never leaves a projection whose generation is gone.
///
/// The three candidate-observation tables (#209) are copied for the strongest
/// reason on this list: a reviewed relevance judgment is human work, and the
/// bounded passage it was made against is a snapshot of content that may
/// since have changed. Neither can be reconstructed from markdown, from the
/// code index, or from anything else on disk.
pub(crate) const COPIED_TABLES: &[&str] = &[
    "code_symbols",
    "indexed_files",
    "code_fts",
    "code_vec",
    "edges",
    "repo_marker",
    "feedback",
    "code_feedback",
    "retrieval_log",
    "feedback_events",
    "activity_log",
    "query_expansions",
    "bandit_arms",
    "eval_runs",
    "gc_runs",
    "index_runs",
    "source_files",
    "documents",
    "document_chunks",
    "document_fts",
    // A pulled revision cannot be re-derived from anything on this disk — the
    // file it describes may not exist here — and the share mapping is the only
    // record of what a local document is called upstream. Both are copied.
    "remote_document",
    "remote_document_chunk",
    "remote_document_link",
    "remote_document_fts",
    "document_share",
    "sync_log",
    "sync_state",
    "sync_binding",
    // Server state, not local state: dropping it would leave every shared
    // document withheld until the next policy load, which a rebuild gives no
    // sign of needing.
    "repository_approval",
    "candidate_query_observations",
    "candidate_observations",
    "candidate_judgments",
    "replica_stream",
    "replica_device",
    "replica_payload",
    "replica_feed",
    "replica_revision",
    "replica_operation",
    "replica_receipt",
    "replica_cursor",
    "memory_needs_embedding",
    "code_generation",
    "remote_code_file",
    "remote_code_symbol",
    "remote_code_edge",
];

/// Live tables a rebuild deliberately does not copy, each with its reason.
/// Every live table must appear in [`COPIED_TABLES`] or here — the
/// coverage test's other half.
pub(crate) const RECONSTRUCTABLE_TABLES: &[(&str, &str)] = &[
    ("memories", "replayed from memories/*.md"),
    ("memory_tags", "replayed from frontmatter"),
    ("memory_fts", "rebuilt by memory_row::insert"),
    (
        "memory_substring",
        "rebuilt by triggers during memory replay",
    ),
    ("memory_vec", "BYO-vector contract: caller re-embeds"),
    ("code_ref", "materialized from frontmatter references"),
    (
        "edge_fts",
        "regenerated by graph::derived::refresh_derived_best_effort",
    ),
    (
        "index_failures",
        "transient per-run index error log; not user data",
    ),
    (
        "source_roots",
        "reconciled from sources.toml by source::mirror",
    ),
    ("schema_meta", "owned by the migration runner"),
    (
        "replica_staged_part",
        "incomplete uploads; a peer re-stages what it never activated",
    ),
    (
        "memory_write_intent",
        "a rebuild replays every memory from markdown, which is the \
         reconciliation an outstanding intent would ask for",
    ),
];

/// Run the allowlist sanity check, then attach `old_db` and copy every
/// preserved table into `conn` via [`crate::store::rebuild_copy`].
///
/// Caller must populate `main.source_roots` first
/// (`source::mirror::reconcile`, in [`super::build_new_db`]).
pub(crate) fn copy_preserved_tables_from_old(conn: &mut Connection, old_db: &Path) -> Result<()> {
    // Debug-only, and deliberately so: the authoritative check is
    // `migration_integrity_every_live_table_is_covered_exactly_once` in
    // `tests/coverage.rs`, which also proves the union covers the live set.
    // This assertion is not a runtime guard — it is what gives both consts a
    // real consumer in the non-test build, so neither can drift into
    // dead code while the coverage test still appears to pass.
    debug_assert!(
        COPIED_TABLES
            .iter()
            .all(|t| !RECONSTRUCTABLE_TABLES.iter().any(|(r, _)| r == t)),
        "a live table cannot appear in both COPIED_TABLES and RECONSTRUCTABLE_TABLES"
    );
    crate::store::rebuild_copy::copy_preserved_tables_from_old(conn, old_db)
}

#[cfg(test)]
#[path = "tests/coverage.rs"]
mod tests;
